### ISSUE TITLE
Stack Level Deep Error on most operations

### ISSUE THREAD

**Issue by zacheryph** [rubyworks/vanunits#1]
Trying to use van/units on ruby 1.9.2 doing most operations i get a SystemStackError for stack level too deep.  if i do '1.mile' in console i get a response but doing 'x = 1.mile' causes the error also.  this is happening at lib/van/units/base.rb:847.

ruby-1.9.2-p136 :001 > require 'van/units'
 => true 
ruby-1.9.2-p136 :002 > include Van::Units
 => Object 
ruby-1.9.2-p136 :003 > 1.mile
 => 1 mile 
ruby-1.9.2-p136 :004 > x = 1.mile
/Users/context/.rvm/gems/ruby-1.9.2-p136/gems/vanunits-1.5.0/lib/van/units/base.rb:847: stack level too deep (SystemStackError)
/Users/context/.rvm/gems/ruby-1.9.2-p136/gems/vanunits-1.5.0/lib/van/units/base.rb:847: stack level too deep (SystemStackError)

**Comment by trans** [comment]
That's a very strange bug. It doesn't seem like it should be possible.

Maybe Peter can chime in here with his thoughts. I'm inclined to report it as bug of Ruby itself.

FYI, vanunits isn't really being actively maintained any longer --at least not by me. I've moved on to [Stick](http://github.com/rubyworks/stick), although unfortunately I haven't had any time in quite a while to work on it --but just the same, that's where the future of my unit system work lies. OTOH, Peter, who wrote almost all of vanunits, might have other ideas. Regardless, that's still no reason for the vanunits not to be working, it's pretty well tested and feature complete for what it was designed to do.

**Comment by calamitas** [comment]
This only happens in irb, and it is not the 1.mile part that is the problem; after the "include Van::Units", any assignment in irb hangs, so this reproduces the problem:

ruby-1.9.2-p180-fastrequire :003 > require 'van/units'
 => true 
ruby-1.9.2-p180-fastrequire :004 > x = 1
 => 1 
ruby-1.9.2-p180-fastrequire :005 > include Van::Units
 => Object 
ruby-1.9.2-p180-fastrequire :006 > x = 1
/Users/peter/programming/vanunits/lib/van/units/base.rb:847: stack level too deep (SystemStackError)
/Users/peter/programming/vanunits/lib/van/units/base.rb:847: stack level too deep (SystemStackError)

It must be because of the methods in Van::Units, but I'll have to look further to find out what exactly is the problem.

**Comment by calamitas** [comment]
The smallest code to reproduce the bug is the following:

``` ruby
class ::Object

  def method_missing(m, *a, &b)
    super
  rescue ::Exception => e
    raise e
  end

end

1.foo
```

In Ruby 1.8.6, the method_missing definition is a no-op as all it does is just reproduce the original behavior. On 1.9, this causes an infinite loop. The reason for this is that Ruby 1.9 calls to_str on the exception object, but as this method is not defined, it calls the method_missing again, causing a nice infinite loop.

**Comment by calamitas** [comment]
Actually, the simplest case looks to be this:

``` ruby
class ::Object

  def method_missing(m, *a, &b)
    raise ArgumentError.new("haha")
  end

end

1.foo
```

I'd say now that it might be a bug in Ruby; I'll post it on ruby-core.

**Comment by trans** [comment]
I'm glad you figured that out. Certainly is not obvious. And yes, I'd say it's a _bug_ in Ruby.

**Comment by calamitas** [comment]
No answer yet on ruby-core.

I will see if I can add a fix without the need for changes to Ruby. Even if they fix the bug, it will take a while before users actually have that fix on their machines.

**Comment by trans** [comment]
They aren't responding to a number of issues these days it seems :-(
